// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aktjcpdrdtqhmylklrgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrdGpjcGRyZHRxaG15bGtscmd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1OTI1NTYsImV4cCI6MjA2MzE2ODU1Nn0.WtabvsTSI3c_jwXRO_U_znjVT6abgRxHLzw1D3mP1mI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);